### PR TITLE
Intermediate HTML and CSS -More Text Styles: Refactor lesson to comply with style guide

### PR DESCRIPTION
**Pull request by fabulousgk**
## Because

This lesson lacks an assignment section, which is required as part of the style guide.  It also has some strong language about Google fonts that needs to be moderated at bit.

## This PR

- Refactor lesson to comply with style guide
- Rewrite GDPR information to be more neutral
- Adds some new links as assignments and additional resources.

## Issue

Closes #27241

## Additional Information

This is a big set of changes on this lesson, please give feedback as appropriate.

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If any lesson files are included in this PR, they have been previewed with the [Markdown preview tool](https://www.theodinproject.com/lessons/preview) to ensure it is formatted correctly
-   [x] If any lesson files are included in this PR, they follow the [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md)

### CODE REVIEW

**Comment by MaoShizhong** [comment]
Just noticed this - you may want to re-PR this to be pulled into [TheOdinProject:main](https://github.com/TheOdinProject/curriculum/tree/main), as you've accidentally PRed to main in your fork.

**Comment by fabulousgk** [comment]
OMG. I wondered why this was not getting comments.  Will address tomorrow

**Comment by MaoShizhong** [comment]
@fabulousgk Looks like you've another PR that fell victim to the same thing :P

**Comment by fabulousgk** [comment]
I just saw that, not sure what happened.  Real weird

**Pull request closed without merging**
